# Generated by Django 4.0.4 on 2022-04-16 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('subcategory', models.CharField(blank=True, max_length=25)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('entry_date', models.DateField()),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
